### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by mario** [anjlab/android-inapp-billing-v3#15]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=null} to activity {com.lovelyhq.android.lovelydocs/com.lovelyhq.android.lovelydocs.controllers.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3351)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3394)
at android.app.ActivityThread.access$1300(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.anjlab.android.iab.v3.BillingProcessor.boolean handleActivityResult(int,int,android.content.Intent)(:234)
at com.lovelyhq.android.lovelydocs.controllers.MainActivity.void onActivityResult(int,int,android.content.Intent)(:527)
at android.app.Activity.dispatchActivityResult(Activity.java:5423)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3347)
... 11 more

**Comment by dotnick** [comment]
I'm getting reports for the same issue:

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=Intent { (has extras) }} to activity {my.activity}: java.lang.NullPointerException

Any ideas?

**Comment by MikeRzDev** [comment]
same as dotnick
