### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by timothyjc** [anjlab/android-inapp-billing-v3#164]
I have an app in beta and there are a handful of ANRs coming out of here:

at android.os.BinderProxy.transactNative(Native method)
  at android.os.BinderProxy.transact(Binder.java:496)
  at com.android.vending.billing.IInAppBillingService$Stub$Proxy.getSkuDetails(IInAppBillingService.java:250)
  at com.anjlab.android.iab.v3.BillingProcessor.getSkuDetails(BillingProcessor.java:318)
  at com.anjlab.android.iab.v3.BillingProcessor.getPurchaseListingDetails(BillingProcessor.java:355)

In onResume I am checking if mBillingProcessor.isInitialized();
then mBillingProcessor.loadOwnedPurchasesFromGoogle();
then if loaded I call mBillingProcessor.getPurchaseListingDetails(productIds);
which is where the ANR happens.
I am doing all this on the main thread and it works fine almost always, except for a handful of ANRs in the logs. Should this be done off the main thread?

**Comment by azakhary** [comment]
+1 currently investigating same thing. This is a pretty major issue, having 20% of users drop off on app start because of ANR

**Comment by azakhary** [comment]
Found this:
http://developer.android.com/google/play/billing/billing_integrate.html

> Warning: Do not call the getSkuDetails method on the main thread. Calling this method triggers a network request which could block your main thread. Instead, create a separate thread and call the getSkuDetails method from inside that thread.

**Comment by timothyjc** [comment]
Ah nice find. I also notice they say the same for consumePurchase:

Warning: Do not call the consumePurchase method on the main thread. Calling this method triggers a network request which could block your main thread. Instead, create a separate thread and call the consumePurchase method from inside that thread.

**Comment by Slamper** [comment]
We are currently experienceing something similar.

Has anyone been able to resolve this issue yet ?
```
 	at android.os.BinderProxy.transact(Native Method)
 	at com.a.a.a.c.a(IInAppBillingService.java:405)
 	at com.anjlab.android.iab.v3.c.a(BillingProcessor.java:160)
 	at com.anjlab.android.iab.v3.c.e(BillingProcessor.java:187)
 	at com.anjlab.android.iab.v3.c$1.onServiceConnected(BillingProcessor.java:87)
```

**Comment by azakhary** [comment]
yeah, just called that in separate thread, and all was awesome.

**Comment by Slamper** [comment]
@azakhary thank you
Our issue was that we initialized the Billing framework on another thread. We now moved the initialization to the MainThread and everything seems to work just fine.
All other calls are done on separate threads

**Comment by serggl** [comment]
closing this in flavour of #191
