### ISSUE TITLE
Payment Confirmation Dialog isn't appearing.

### ISSUE THREAD

**Issue by SeniorCoder1025** [anjlab/android-inapp-billing-v3#169]
I've implemented IAB and test it on alpha test channel.
When start to test it, payment works well, but after certain number of payment, confirm dialog isn't appearing.
https://www.youtube.com/watch?v=Eo0182R2nO8
Please help me how to show the confirmation dialog for every purchase.

**Comment by jcdom** [comment]
There is a method to consume a purchased product.
If you don't consume a product, when you try to purchase again, a code error 7 is received from Google Play.
All response codes here:
http://developer.android.com/intl/es/google/play/billing/billing_reference.html
Info about consuming In-app Products:
http://developer.android.com/intl/es/google/play/billing/api.html

**Comment by SeniorCoder1025** [comment]
There is no error, as you see the video.
Purchase works well and called success callback function.
The problem is only not showing confirmation dialog.

**Comment by serggl** [comment]
seem like there is some issue with contexts, like you call purchase passing it an inactive activity. But thats a guess. Too few info to help you

**Comment by btwarog** [comment]
Hi I have got the same issue, you may be right with this inactive activity, but why it's getting inactive, on 5x it work like it suppose to, but for example on Samsung s7, it is not.  I've noticed in my previous implementations that when I wanted to show user progress dialog - after item was successfully purchased - dialog appeared only on 5x, on Samsung there was an error in _logcat_, that it could not show progress after _onSaveInstanceState_. I am going to see if it is caused by this library, by implementing inapp without it.

**Comment by serggl** [comment]
@jcdom can you share your logcat's output ?

**Comment by btwarog** [comment]
That's appearing on Samsung when making purchase

Activity methods called on Samsung during the purchase:
onPause
onSaveInstanceState
onResume


Activity methods called on Nexus during the purchase:
onPause
onResume

`01-27 08:50:46.141 3450-4298/? E/Parcel: Class not found when unmarshalling: com.google.android.finsky.billing.lightpurchase.PurchaseParams
                                         java.lang.ClassNotFoundException: com.google.android.finsky.billing.lightpurchase.PurchaseParams
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6195)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161)
                                             at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6855)
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310)
                                             at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6613)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.google.android.finsky.billing.lightpurchase.PurchaseParams
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6195) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161) 
                                             at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6855) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310) 
                                             at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6613) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by serggl** [comment]
maybe a proguard issue?

**Comment by btwarog** [comment]
Maybe, but it appears in logs when you use no filters. When you filtering them by showing only logs related to app, the this log isn't visible. For me it looks like something is wrong with producer's system overlay.
