### ISSUE TITLE
NoClassDefFoundError: android/os/AsyncTask

### ISSUE THREAD

**Issue by ankitbatra11** [anjlab/android-inapp-billing-v3#227]
I have following issue reported from field on android 4.0.3:

Fatal Exception: java.lang.NoClassDefFoundError: android/os/AsyncTask
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(SourceFile:114)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1068)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1085)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by serggl** [comment]
are you using proguard?

**Comment by ankitbatra11** [comment]
Yes.

**Comment by ankitbatra11** [comment]
Yes

**Comment by serggl** [comment]
Then add an exception rule to the proguard config

**Comment by ankitbatra11** [comment]
Why other Android versions do not report it if that's the case?

**Comment by serggl** [comment]
I dont know the details of your case. All I can say that AsyncTask is supported starting from Android 1.5 so there must be something in the way you bundle your APK
