### ISSUE TITLE
Nullpointer when creating BillingProcessor

### ISSUE THREAD

**Issue by code-mc** [anjlab/android-inapp-billing-v3#23]
Everything works as it should when I compile and run my apk, but once I generate the signed apk and run that I always get the following error when I initialize the BillingProcessor:

```
java.lang.NullPointerException
        at re.getPreferencesBaseKey(SourceFile:36)
        at rf.c(SourceFile:41)
        at rf.d(SourceFile:45)
        at rf.<init>(SourceFile:37)
        at com.anjlab.android.iab.v3.BillingProcessor.<init>(SourceFile:88)
        at net.steamcrafted.craftable2.app.act.MainActivity.setupAds(SourceFile:325)
        at net.steamcrafted.craftable2.app.act.MainActivity.onCreate(SourceFile:207)
        at android.app.Activity.performCreate(Activity.java:5241)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
        at android.app.ActivityThread.access$800(ActivityThread.java:145)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5081)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ompemi** [comment]
I am not using Proguard, and it is still happening to most of our users. Have a look at the crash here: http://crashes.to/s/9de74f5138e

The only change is to call `getPurchaseListingDetails` in a separate thread (and also `bp.loadOwnedPurchasesFromGoogle();`)
