### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from field 'com.anjlab.android.iab.v3.PurchaseInfo com.anjlab.android.iab.v3.TransactionDetails.purchaseInfo' on a null object reference

### ISSUE THREAD

**Issue by almaz010891** [anjlab/android-inapp-billing-v3#235]
Hi! I got an NullPointerException when app launch first time after installation
```
java.lang.NullPointerException: Attempt to read from field 'com.anjlab.android.iab.v3.PurchaseInfo com.anjlab.android.iab.v3.TransactionDetails.purchaseInfo' on a null object reference
at com.alex.core.activity.MainActivity.onPurchaseHistoryRestored(MainActivity.java:473)
    at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.onPostExecute(BillingProcessor.java:98)
    at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.onPostExecute(BillingProcessor.java:80)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
My code below
```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        bp = new BillingProcessor(this, StringUtils.reverse(BillingUtils.getKey()), this);
}

    @Override
    public void onBillingInitialized() {
        bp.loadOwnedPurchasesFromGoogle();
    }

    @Override
    public void onPurchaseHistoryRestored() {
        TransactionDetails transactionDetails = bp.getPurchaseTransactionDetails(BillingUtils.SKU_ADS_DISABLE);
        PurchaseState purchaseState = transactionDetails.purchaseInfo.purchaseData.purchaseState;
        if (purchaseState == PurchaseState.Canceled && purchaseState == PurchaseState.Refunded)
            BillingUtils.setPurchased(this, false);
        if (bp != null)
            bp.release();
    }
```

**Comment by Zennaxxtech** [comment]
Any update in this because i have same issue. Please do some help if you got solution because i am facing this issue last 3 days?

**Comment by mrsr2win** [comment]
i got same problem

**Comment by mrsr2win** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.bitwire.torrent, PID: 16873
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.bitwire.torrent/co.we.torrent.presentation.activities.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.anjlab.android.iab.v3.BillingProcessor co.we.torrent.AndroidApplication.billingProcessor' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'com.anjlab.android.iab.v3.BillingProcessor co.we.torrent.AndroidApplication.billingProcessor' on a null object reference
        at co.we.torrent.AndroidApplication.isProVersion(AndroidApplication.java:150)
        at co.we.torrent.presentation.main.ui.MainFragment.onActivityCreated(MainFragment.java:312)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2355)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at co.we.torrent.presentation.activities.MainActivity.onStart(MainActivity.java:43)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1341)
        at android.app.Activity.performStart(Activity.java:7200)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by salmankhalid876** [comment]
Any solution?
