### ISSUE TITLE
Rarely the DeadObjectException thrown from loadOwnedPurchasesFromGoogle()

### ISSUE THREAD

**Issue by mvysny** [anjlab/android-inapp-billing-v3#236]
Do you want to request a **feature** or report a **bug**?
bug

What is the current behavior?
Randomly (I cannot reproduce this on my phone, but Crashlytics occasionally reports this crash to my console) the Billing library fails to initialize, calls onBillingError with error code 100 and the following stacktrace:

```
android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:496)
       at com.android.vending.billing.IInAppBillingService$Stub$Proxy.getPurchases(IInAppBillingService.java:405)
       at com.anjlab.android.iab.v3.BillingProcessor.loadPurchasesByType(BillingProcessor.java:190)
       at com.anjlab.android.iab.v3.BillingProcessor.loadOwnedPurchasesFromGoogle(BillingProcessor.java:217)
       at sk.baka.photoframe.InAppPurchases$1.onBillingInitialized(InAppPurchases.java:99)
       at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.onPostExecute(BillingProcessor.java:101)
       at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.onPostExecute(BillingProcessor.java:80)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

If the current behavior is a bug, **please provide the steps to reproduce** and if possible a minimal demo of the problem or a code snippet.
Don't forget to mention:
- which version of library you use
com.anjlab.android.iab.v3:library:1.0.38

- was it working in previous versions?
I do not know, unfortunately

- do you use fragments or not
Yes

- how do you instanciate `BillingProcessor` (singleton or not)
Yes, effectively a singleton - instantiated once (new BillingProcessor) in MultiDexApplication.onCreate()

- which device/OS version do you use for testing (or its an emulator)
Android 5.1.1, Nexus 7, not rooted

- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha)
Yes, Production

- do you test with real products, or with a testing onces (e.g. `android.test.purchased`)
Real products; the app is in production and Billing library works flawlessly, apart from rare DeadObjectExceptions.

The more details you provide - the faster you'll get an answer from community
onBillingInitialized() is called properly and it looks like this:
```
            @Override
            public void onBillingInitialized() {
                log.info("onBillingInitialized()");
                if (bp.loadOwnedPurchasesFromGoogle()) {
                    updatePurchaseStatus();
                }
            }
```

If you have a **general question**, please flag it in the title: "Question: how do I ..."

**Comment by mvysny** [comment]
Thank you so much for your library. The moronic Google Play API is next to unusable, but thanks to your library I was able to manage the in-app purchases.

**Comment by autonomousapps** [comment]
Unfortunately, I don't think there's much we can do about a `DeadObjectException`. Best thing to do is probably re-init the library and try again.

Closing for now, but feel free to re-open if there's any action we can take.
