### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.anjlab.android.iab.v3.BillingProcessor.purchase(android.app.Activity, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by conzorz** [anjlab/android-inapp-billing-v3#245]
at ...
 at android.view.View.performClick(View.java:5637)
 at android.view.View$PerformClick.run(View.java:22433)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6126)
 at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by serggl** [comment]
seem like an error in your code @conzorz (based on the issue title)

**Comment by omidMolaverdi** [comment]
Hi @conzorz,

Did you find a solution for this?
