### ISSUE TITLE
[Bug] Purchase crashes

### ISSUE THREAD

**Issue by cbrevik** [anjlab/android-inapp-billing-v3#290]
Hi there, thanks for the great library!

We're actually wrapping this library in a [React Native module](https://github.com/idehub/react-native-billing). It is basically a wrapper between the JavaScript-side of RN, and the native side of this library.

Currently having an issue with `1.0.36` of this library, where calling `purchase` makes it crash ("Unfortunately, Google Play Store has stopped"). Our wrapper has been working fine for quite some time, but suddenly a lot of users is reporting crashes with `purchase`: https://github.com/idehub/react-native-billing/issues/66

`adb logcat` gives me the following:
```
E/AndroidRuntime(12126): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(12126): Process: com.android.vending, PID: 12126
E/AndroidRuntime(12126): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(12126): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(12126): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(12126): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(12126): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(12126): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12126): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12126): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(12126): Caused by: java.lang.NullPointerException: Attempt to read from field 'long com.google.wireless.android.finsky.dfe.nano.an.b' on a null object reference
E/AndroidRuntime(12126): 	at com.google.android.finsky.billing.lightpurchase.s.a(SourceFile:5)
E/AndroidRuntime(12126): 	at com.google.android.finsky.billing.lightpurchase.h.doInBackground(SourceFile:27)
E/AndroidRuntime(12126): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(12126): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(12126): 	... 3 more
V/ApplicationPolicy(  893): isApplicationStateBlocked userId 0 pkgname com.android.vending
W/ActivityManager(  893):   Force finishing activity com.android.vending/com.google.android.finsky.billing.lightpurchase.IabV3Activity
W/ActivityManager(  893):   Force finishing activity com.billingtest/.MainActivity
```

Because of the asynchronous nature of the React Native-bridge, we have to use JavaScript `Promises` to communicate with the JS side. The consumer of our module calls the [`open`](https://github.com/idehub/react-native-billing/blob/a2c8a003944c90b767b83ccf6cec6d75d367f2aa/android/src/main/java/com/idehub/Billing/InAppBillingBridge.java#L67-L86) method, which instantiates the `BillingProcessor`. When that `Promise` is resolved, they can call the [`purchase`](https://github.com/idehub/react-native-billing/blob/a2c8a003944c90b767b83ccf6cec6d75d367f2aa/android/src/main/java/com/idehub/Billing/InAppBillingBridge.java#L131-L143) method.

I've stepped through the BillingProcessor, and the error seems to occur after/at [this line](https://github.com/anjlab/android-inapp-billing-v3/blob/8954265d7ff88720221abfb0668c8e1f57faa9de/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L656).

This happens for both debug/release apps, with both real and test products, on multiple devices.

The weird thing is, we haven't updated our module or its dependencies in quite a while. Which makes me think maybe Google has done something differently. Because it is happening to a lot of different users at the same time. I've tried upgrading the dependency of `android-inapp-billing-v3` to `1.0.43` without it seeming to help.

Any ideas?

**Comment by dskato** [comment]
I have the same error Have you found a solution?

**Comment by serggl** [comment]
Hard to guess...
The only guess I have so far is that you use `ReactApplicationContext reactContext` to instantiate BillingProcessor. Is this an activity context or an application context? I think an activity context is required here...

**Comment by cbrevik** [comment]
Hi @serggl. Thanks for your answer.

That is the React Native application context. I've tried switching the instantiation of `BillingProcessor` to instead use the Activity context: `bp = new BillingProcessor(getCurrentActivity(), LICENSE_KEY, this);`.

But, sadly I'm getting the same error. Weird thing is, this has been working fine for many months without any changes.

I am unsure at this point if this is just related to test product ids like `android.test.purchased`, or if it is happening to real ones as well. (Maybe a bit of miscommunication from the users of my module, will have to get back to you about that).

**Comment by mp205** [comment]
Hello, this is not related only to react.
I am developing native java app and I get this error too, even on **real** product IDs with app in _alpha channel_

**Comment by autonomousapps** [comment]
I am using version 1.0.40 in a project with over 200k daily users, and I never see this crash. Maybe it's a usage issue...?

**Comment by deepakrana0011** [comment]
Hello , i am implementing this in native app and getting the same crash . I think it is the problem with the testing product id . Because i have  implement this API in the previous projects and it is still working fine on those projects but only difference is they are live on play store.
