### ISSUE TITLE
Error Purchase

### ISSUE THREAD

**Issue by vladimirmedyannikov** [anjlab/android-inapp-billing-v3#309]
The error is only reproduced for purchases.
In Google Play purchase is status "Purchased", but when handle result NPE.

**Info:**
E/iabv3: Error in handleActivityResult
                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                      at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                      at org.json.JSONObject.<init>(JSONObject.java:156)
                                                      at org.json.JSONObject.<init>(JSONObject.java:173)
                                                      at com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(BillingProcessor.java:932)

**Comment by ratm** [comment]
I have the same issue when testing, basically _data.getStringExtra(Constants.INAPP_PURCHASE_DATA)_ and _data.getStringExtra(Constants.RESPONSE_INAPP_SIGNATURE)_ are both returning **null**

I'm not sure how it's possible. Will try to investigate further.

**Comment by ratm** [comment]
@vladimirmedyannikov I had this error when calling purchase() on a subscription iap.
Fixing my code to properly call subscribe() when needed fixed the problem.

**Comment by Zennaxxtech** [comment]
Please check that still i am facing this issue [#258](https://github.com/anjlab/android-inapp-billing-v3/issues/258)
