### ISSUE TITLE
An error occured while executing doInBackground

### ISSUE THREAD

**Issue by Verteletsky** [anjlab/android-inapp-billing-v3#366]
Hello! My application is in beta, published in the market, google tests it and finds problems, here is one of them:

report a **bug**

Don't forget to mention:
- which version of library you use ('com.anjlab.android.iab.v3:library:1.0.44')
- was it working in previous versions? ('I don't know')
- do you use fragments or not ('No')
- how do you instanciate `BillingProcessor` (singleton or not) (Yes)
- which device/OS version do you use for testing (Google Device, read below)
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha) (Yes, Beta)
- do you test with real products, or with a testing onces (e.g. `android.test.purchased`) (read products)

Device:
Model - Galaxy J1 Ace
RAM - 1024 MB
Manufacturer - Samsung
OpenGL ES - 2.0
Android version - Android 5.1
Main Platform - armeabi-v7a
Regional Settings - ru_RU
Brand CP - Spreadtrum
CPU model - SC9830I

`Проблема: java.lang.RuntimeException: An error occured while executing doInBackground()
FATAL EXCEPTION: AsyncTask #1
Process: ru.nowandroid.cryptohodl, PID: 13019
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:200)
	at android.os.Handler.<init>(Handler.java:114)
	at android.widget.Toast$TN.<init>(Toast.java:645)
	at android.widget.Toast.<init>(Toast.java:137)
	at android.widget.Toast.makeText(Toast.java:440)
	at ru.nowandroid.cryptohodl.MainActivity.showToast(MainActivity.kt:170)
	at ru.nowandroid.cryptohodl.MainActivity.onBillingError(MainActivity.kt:58)
	at com.anjlab.android.iab.v3.BillingProcessor.reportBillingError(BillingProcessor.java:1016)
	at com.anjlab.android.iab.v3.BillingProcessor.loadPurchasesByType(BillingProcessor.java:304)
	at com.anjlab.android.iab.v3.BillingProcessor.loadOwnedPurchasesFromGoogle(BillingProcessor.java:317)
	at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.doInBackground(BillingProcessor.java:102)
	at com.anjlab.android.iab.v3.BillingProcessor$HistoryInitializationTask.doInBackground(BillingProcessor.java:95)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more`

**Comment by moisoni97** [comment]
Have you solved it?

**Comment by Verteletsky** [comment]
@moisoni97 yeah, my telegram @vendetta_dev
