### ISSUE TITLE
Fatal error: NullPointerException

### ISSUE THREAD

**Issue by nikitoSha** [anjlab/android-inapp-billing-v3#431]
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
       at com.anjlab.android.iab.v3.BillingProcessor.getPurchaseHistory(BillingProcessor.java:1098)
       at ru.str.fcalldetector.MainActivity$8.doOnBackground(MainActivity.java:357)
       at com.arasthel.asyncjob.AsyncJob$2.run(AsyncJob.java:59)
       at java.lang.Thread.run(Thread.java:818)

Code:

	AsyncJob.doInBackground(new AsyncJob.OnBackgroundJob() {
		@Override
		public void doOnBackground() {
			if (!isSubscriprionOK(purchaseResult) && !HelpFuncs.canShowLogOrNotifi(thisActivityContext)){
				showNeedPayDialog();
			}else{
				try {
					List<BillingHistoryRecord> previousPurchases =
							bp.getPurchaseHistory(Constants.PRODUCT_TYPE_SUBSCRIPTION, new Bundle());
					long lastPurchaseTime = 0L;
					int purchArrayIndex = 0;
					for (BillingHistoryRecord thisPurchase: previousPurchases) {
						if (thisPurchase.purchaseTime > lastPurchaseTime){
							lastPurchaseTime = thisPurchase.purchaseTime;
							purchArrayIndex = previousPurchases.indexOf(thisPurchase);
						}
					}
					if (previousPurchases.size() > 0) {
						BillingHistoryRecord thisPurchase = previousPurchases.get(purchArrayIndex);
						TransactionDetails purchDetails = bp.getSubscriptionTransactionDetails(thisPurchase.productId);
						if (purchDetails != null) {
							if (!purchDetails.purchaseInfo.purchaseData.autoRenewing) {
								HelpFuncs.setPayed(thisActivityContext, true);
								LogHelper.info(MainActivity.class, "Подписка оплачена (2)");
							} else {
								HelpFuncs.setPayed(thisActivityContext, false);
								LogHelper.info(MainActivity.class, "Подписка не оплачена! (2)");
								showNeedPayDialog();
							}
						}
					}else{
						HelpFuncs.setPayed(thisActivityContext, false);
						LogHelper.info(MainActivity.class, "Подписка не оплачена! (3)");
						showNeedPayDialog();
					}
				} catch (BillingCommunicationException e) {
					e.printStackTrace();
				}
			}
		}
	});

Exception on line:

> bp.getPurchaseHistory(Constants.PRODUCT_TYPE_SUBSCRIPTION, new Bundle());

**Comment by nikitoSha** [comment]
Place with exception:

https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L1098
