### ISSUE TITLE
Null pointer exception in onActivityResult

### ISSUE THREAD

**Issue by Mateeen** [anjlab/android-inapp-billing-v3#453]
this is the stack trace 
Devices
60% HUAWEI
Operating systems
80% Android 10-9
Device states
0% background
60%
HUAWEI
20%
TECNO MOBILE LIMITED
20%
Xiaomi

Caused by java.lang.NullPointerException: throw with null exception
       at com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(BillingProcessor.java:40)
       at com.example.MainActivity.onActivityResult(MainActivity.java:331)
       at android.app.Activity.dispatchActivityResult(Activity.java:8412)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5580)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5628)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by Nutza97** [comment]
W
