### ISSUE TITLE
BUG - NullPointerException - com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult

### ISSUE THREAD

**Issue by fabiofrack** [anjlab/android-inapp-billing-v3#469]
Hello guys,

We update our apps that using this library and, without touching the code we faced these errors on many devices, reported by crashlytics, we can't reproduce it. We're in prod channel.

Our doubt is that this is correlated to some update in the App Gradle but can't understand how can damage the billing library. 

The working version contains:
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
    implementation 'com.google.android.gms:play-services-ads:19.5.0'

The version that, sometimes crashes contain
    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'
    implementation 'com.google.android.gms:play-services-ads:19.6.0'

We're using:
    implementation 'com.anjlab.android.iab.v3:library:1.1.0'

Complete log error:
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=232, result=0, data=null} to activity {myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(int, int, android.content.Intent)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(int, int, android.content.Intent)' on a null object reference
       at myapp.MainActivity.onActivityResult(MainActivity.java:3255)
       at android.app.Activity.dispatchActivityResult(Activity.java:8413)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by fabiofrack** [comment]
My fault.

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by valeciawolf34** [comment]
Vwolf_ua@nec.edu and and I have been working on the welcome-orb for the
last few days and I have been working on the welcome-orb for the last

Valecia G Rodriguez

**Comment by valeciawolf34** [comment]
:heart_eyes:

**Comment by valeciawolf34** [comment]
<iframe title="vimeo-player" src="https://player.vimeo.com/video/494126300" width="640" height="360" frameborder="0" allowfullscreen></iframe>

**Comment by valeciawolf34** [comment]
<iframe title="vimeo-player" src="https://player.vimeo.com/video/494126300"
width="640" height="360" frameborder="0" allowfullscreen></iframe>

Valecia G Rodriguez
