### ISSUE TITLE
Acknowledge not working

### ISSUE THREAD

**Issue by UlisesSwingU** [anjlab/android-inapp-billing-v3#507]
**bug**

For all subscriptions the billing processor is returning `errorCode = 115`

I'm instantiating the billing processor with `BillingProcessor.newBillingProcessor(context, key, handler)`

and the answer is always 
 ``` W/System.err: java.lang.Throwable: Billing error not handled: 115
      W/System.err:     at com.mypackage.MyActivity$4.onBillingError(BaseUpgradeActivity.java:258)
      W/System.err:     at com.anjlab.android.iab.v3.BillingProcessor.reportBillingError(BillingProcessor.java:1052)
      W/System.err:     at com.anjlab.android.iab.v3.BillingProcessor.access$1100(BillingProcessor.java:42)
      W/System.err:     at com.anjlab.android.iab.v3.BillingProcessor$18.onAcknowledgePurchaseResponse(BillingProcessor.java:1152)
      W/System.err:     at com.android.billingclient.api.BillingClientImpl.zzo(com.android.billingclient:billing@@4.0.0:12)
      W/System.err:     at com.android.billingclient.api.zzk.call(Unknown Source:6)
      W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

I can se the acknowledge implementation in  the library but no related configuration in the documentation

**Comment by UlisesSwingU** [comment]
Also I found this happens only in release versions, debug versions do not throw this error and acknowledge is successful

**Comment by serggl** [comment]
Was it error 110 maybe?
I found that `onProductPurchased` wasn't invoken on the main thread, and thus if you tried to update views in your `onProductPurchased` - it would crash
Uploaded 2.0.2 to maven central

**Comment by UlisesSwingU** [comment]
Is `115`, I have seen that this happens sometimes when using` BillingProcessor.newBillingProcessor(context, key, handler)` in different fragments and activities, as if the callback get registered multiple times and for the first the purchase is complete and validated but for the callback  where the token of the purchases is used to acknowledge the purchase this returns `115` because the token has been already used to acknowledge the first purchase.
So maybe I'm missing a `release()` in the destroy of an activity or fragment.

But I would like to know if there is a way to avoid this in the pattern of having a processor in the activity and another in the fragments because we need different callbacks in each one.

**Comment by bierzorutas** [comment]
Exact same problem here, any clue ?
