### ISSUE TITLE
Security Exception in android 14 not resolved in v2.0.3

### ISSUE THREAD

**Issue by najam-jas-android** [anjlab/android-inapp-billing-v3#545]
Do you want to request a **feature** or report a **bug**?
**Bug**
What is the current behavior?
App is crashing due to security of broadcast receiver
If the current behavior is a bug, **please provide the steps to reproduce** and if possible a minimal demo of the problem or a code snippet.
Initilize Billing Processor
Don't forget to mention:
- which version of library you use  **v2.0.3**
- was it working in previous versions?  **it working good till android 13 but crashing in android 14**
- do you use fragments or not -
- how do you instanciate `BillingProcessor` (singleton or not)  **singleton**
- which device/OS version do you use for testing (or its an emulator) -
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha) -
- do you test with real products, or with a testing onces (e.g. `android.test.purchased`) -

**Exception:**
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                            	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                            	at android.os.Parcel.createException(Parcel.java:3053)
                            	at android.os.Parcel.readException(Parcel.java:3036)
                            	at android.os.Parcel.readException(Parcel.java:2978)
                            	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
                            	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
                            	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                            	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                            	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                            	at com.android.billingclient.api.zzg.zzb(com.android.billingclient:billing@@4.0.0:1)
                            	at com.android.billingclient.api.zzh.zzd(com.android.billingclient:billing@@4.0.0:1)
                            	at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@4.0.0:38)
                            	at com.anjlab.android.iab.v3.BillingProcessor.initialize(BillingProcessor.java:281)
                            	at com.anjlab.android.iab.v3.BillingProcessor.<init>(BillingProcessor.java:212)
                            	at com.anjlab.android.iab.v3.BillingProcessor.<init>(BillingProcessor.java:197)
                            	at com.anjlab.android.iab.v3.BillingProcessor.<init>(BillingProcessor.java:191)
        
But google says they fixed issue in 6.0.1
[https://developer.android.com/google/play/billing/release-notes#6-0-1]

**Comment by superoidlau** [comment]
This issue should be fixed, the library's billing version is 6.1.0.
