### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by wparuch** [anjlab/android-inapp-billing-v3#55]
Bug found in Android 2.3.6, Samsung Galaxy S2 mini GT-S6500D after BillingProcessor initialization. I was unable to reproduce it on other devices.

01-05 14:36:56.859: E/AndroidRuntime(16059): FATAL EXCEPTION: main
01-05 14:36:56.859: E/AndroidRuntime(16059): java.lang.NullPointerException
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.anjlab.android.iab.v3.BillingProcessor.isPurchaseHistoryRestored(BillingProcessor.java:352)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.anjlab.android.iab.v3.BillingProcessor.access$100(BillingProcessor.java:38)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:78)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1064)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1081)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.os.Handler.handleCallback(Handler.java:587)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.os.Handler.dispatchMessage(Handler.java:92)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.os.Looper.loop(Looper.java:130)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at android.app.ActivityThread.main(ActivityThread.java:3768)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at java.lang.reflect.Method.invoke(Method.java:507)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
01-05 14:36:56.859: E/AndroidRuntime(16059): 	at dalvik.system.NativeStart.main(Native Method)

BTW. Great library, thanks for developing it ;-).

**Comment by voidstarfire** [comment]
I doubt they'll support such an old device especially on a version of android l less than half a percent use!

**Comment by wparuch** [comment]
Google Play Services supports API 9 and according to the statistics API 10 is 9,1% of all active Android devices:
https://developer.android.com/about/dashboards/index.html

**Comment by serggl** [comment]
@wparuch Im afraid you are the only one who can troubleshoot and fix this issue. I dont have such device...

**Comment by wparuch** [comment]
Android Emulator is widespread available tool ;-). Anyone can easily recreate this problem.

**Comment by serggl** [comment]
Yeah, but I thougth that the IAB is not supported by Android Emulator? Is
rhis the issue you found using emulator?
Пн, 26 янв. 2015 в 2:53, wparuch <notifications@github.com>:

**Comment by ompemi** [comment]
Sorry for the double commenting, as I just commented the same in https://github.com/anjlab/android-inapp-billing-v3/issues/23 

I am not using Proguard, and it is still happening to most of our users. Have a look at the crash here: http://crashes.to/s/9de74f5138e

The only change is to call getPurchaseListingDetails in a separate thread (and also bp.loadOwnedPurchasesFromGoogle();)

**Comment by serggl** [comment]
This is probably because of a WeakReference here: https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/com/anjlab/android/iab/v3/BillingBase.java#L29

How you you initialize BillingProcessor, which `Context` you use for that? Do you use a singleton pattern?
From you stacktrace I only can raise qustions, but not answer :)

**Comment by TheFinestArtist** [comment]
Same issue here TT
```
java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
       at com.anjlab.android.iab.v3.BillingProcessor.isPurchaseHistoryRestored(BillingProcessor.java:352)
       at com.anjlab.android.iab.v3.BillingProcessor.access$100(BillingProcessor.java:38)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:78)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1049)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1066)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:132)
       at android.app.ActivityThread.main(ActivityThread.java:4028)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:491)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by serggl** [comment]
Pull requests are welcome at any time

**Comment by null1099** [comment]
Same here, getting this error on Android 2.3.x - 3.2.1 devices:

```
java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
       at com.anjlab.android.iab.v3.BillingProcessor.isPurchaseHistoryRestored(BillingProcessor.java:383)
       at com.anjlab.android.iab.v3.BillingProcessor.access$100(BillingProcessor.java:38)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:78)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1064)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1081)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3687)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java) 
```

**Comment by serggl** [comment]
closing due to inactivity

**Comment by TheFinestArtist** [comment]
I still has this issue!
```java
Fatal Exception: java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
       at com.anjlab.android.iab.v3.BillingProcessor.isPurchaseHistoryRestored(BillingProcessor.java:432)
       at com.anjlab.android.iab.v3.BillingProcessor.access$100(BillingProcessor.java:41)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:85)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1049)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1066)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:132)
       at android.app.ActivityThread.main(ActivityThread.java:4028)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:491)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by caspii** [comment]
I'm seeing this too:

```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
       at com.anjlab.android.iab.v3.BillingCache.getPreferencesCacheKey(BillingCache.java:44)
       at com.anjlab.android.iab.v3.BillingCache.getPreferencesVersionKey(BillingCache.java:48)
       at com.anjlab.android.iab.v3.BillingCache.getCurrentVersion(BillingCache.java:109)
       at com.anjlab.android.iab.v3.BillingCache.reloadDataIfNeeded(BillingCache.java:113)
       at com.anjlab.android.iab.v3.BillingCache.includesProduct(BillingCache.java:77)
       at com.anjlab.android.iab.v3.BillingProcessor.isPurchased(BillingProcessor.java:139)
       at de.casparwre.insult.HomeScreen$myProgressListener$1.run(HomeScreen.java:491)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)```

**Comment by gaborauth** [comment]
Why are you using WeakReference here?

/library/src/main/java/com/anjlab/android/iab/v3/BillingBase.java:26
private WeakReference<Context> contextReference;

What are the advantages?
