### ISSUE TITLE
NullPointerException at BillingProcessor line 84

### ISSUE THREAD

**Issue by sdeff** [anjlab/android-inapp-billing-v3#61]
I just implemented this library and uploaded my app. Crashlytics is now reporting issues:

Device: SM-N910F (Note 4)
Android: 4.4.4
Rooted: No

Device: C6603
Android: 4.4.4
Rooted: No

java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(SourceFile:84)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1105)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1122)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5748)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

How could this happen even though line 83 checks if (eventHandler != null) ?

Btw. I'm using ProGuard (DexGuard) and I initialize the BIllingProcessor in onCreate of the MainAcitivity like this:

            bp = new BillingProcessor(this, keyString, new BillingProcessor.IBillingHandler() {
                @Override
                public void onProductPurchased(String productId, TransactionDetails details) {
                ...

**Comment by serggl** [comment]
I guess this is an issue with ProGuard configuration, you need to play with Proguard rules.
Try using these rules:
```
-keepattributes *Annotation*
-keep public class com.google.vending.licensing.ILicensingService
-keep public class com.android.vending.licensing.ILicensingService
```
