### ISSUE TITLE
No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms flg=0x80000 pkg=com.android.vending }

### ISSUE THREAD

**Issue by makhazzan** [anjlab/android-inapp-billing-v3#62]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms flg=0x80000 pkg=com.android.vending }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1675)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1467)
at android.app.Activity._logged_startActivityForResult(Activity.java:3467)
at android.app.Activity.startActivityForResult(Activity.java:3460)
at android.app.Activity._logged_startActivityForResult(Activity.java:3420)
at android.app.Activity.startActivityForResult(Activity.java:3414)
at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:840)
at android.app.Activity._logged_startActivity(Activity.java:3702)
at android.app.Activity.startActivity(Activity.java:3691)
at android.app.Activity._logged_startActivity(Activity.java:3662)
at android.app.Activity.startActivity(Activity.java:3656)
at com.google.android.gms.dynamic.a$5.onClick(Unknown Source)
at android.view.View.performClick(View.java:4647)
at android.view.ViewRootImpl.performClickHelper(ViewRootImpl.java:910)
at android.view.ViewRootImpl.performClick(ViewRootImpl.java:919)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3385)
at android.os.Handler.dispatchMessage(Handler.java:122)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5105)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

SDK affected
4.2.2
37%
4.4.2
27%
4.1.2
14%
4.1.1
11%
4.4.3
8%
4.0.4
3%
4.3
3%

**Comment by serggl** [comment]
How can I help you?

**Comment by makhazzan** [comment]
you have 2 hours to fix it

**Comment by serggl** [comment]
:trollface:
