### ISSUE TITLE
BillingProcessor NullPointerException

### ISSUE THREAD

**Issue by TheFinestArtist** [anjlab/android-inapp-billing-v3#66]
Using inapp-billing version 1.0

```
    compile 'com.anjlab.android.iab.v3:library:1.0.+@aar'
```

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=null} to activity {com.utopia.musicoff/com.utopia.musicoff.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3368)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3411)
       at android.app.ActivityThread.access$1300(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5050)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(BillingProcessor.java:297)
       at com.utopia.musicoff.activities.BaseBillingActivity.onActivityResult(BaseBillingActivity.java:107)
       at android.app.Activity.dispatchActivityResult(Activity.java:5423)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3364)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3411)
       at android.app.ActivityThread.access$1300(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5050)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by TheFinestArtist** [comment]
I do have proguard like this
```
-keep class com.android.vending.billing.**
-keepattributes *Annotation*
-keep public class com.android.vending.licensing.ILicensingService
```
