### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by TheFinestArtist** [anjlab/android-inapp-billing-v3#69]
```
java.lang.NullPointerException
       at com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey(BillingBase.java:37)
       at com.anjlab.android.iab.v3.BillingProcessor.isPurchaseHistoryRestored(BillingProcessor.java:352)
       at com.anjlab.android.iab.v3.BillingProcessor.access$100(BillingProcessor.java:38)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:78)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1049)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1066)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:132)
       at android.app.ActivityThread.main(ActivityThread.java:4028)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:491)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by TheFinestArtist** [comment]
Same issue I guess https://github.com/anjlab/android-inapp-billing-v3/issues/55

**Comment by TheFinestArtist** [comment]
Closing duplicated issue!
