### ISSUE TITLE
NullPointerException in onBillingInitialized

### ISSUE THREAD

**Issue by Shajeel-Afzal** [anjlab/android-inapp-billing-v3#83]
Hi!

I got the expectation in onBillingInitialized callback method:

`java.lang.NullPointerException
       at com.shajeelafzal.cricket_app.SettingsActivity.onBillingInitialized(SettingsActivity.java:150)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(BillingProcessor.java:84)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1114)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1131)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5135)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
       at dalvik.system.NativeStart.main(NativeStart.java)`

Can you please tell me what is the reason for this and how to prevent this from happening?

Thanks.

**Comment by serggl** [comment]
you have an NullPointerException in your SettingsActivity.java (line150)
