### ISSUE TITLE
NPE in BillingProcessor

### ISSUE THREAD

**Issue by evgenyh** [anjlab/android-inapp-billing-v3#84]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=null} to activity {my.package/my.package.MyActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3553)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3596)
at android.app.ActivityThread.access$1300(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.anjlab.android.iab.v3.BillingProcessor.a(SourceFile:297)

**Comment by serggl** [comment]
thats a little to few details to help you...

**Comment by evgenyh** [comment]
pls suggest for any other details should I provide.
thanks
